# Generated by Django 3.0.7 on 2023-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
