# Generated by Django 4.2.4 on 2023-08-21 14:22

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ihalar', '0002_auto_20230821_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='iha',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lojistik', 'Lojistik'), ('ARGE', 'ARGE'), ('Sivil ve Ticari', 'Sivil ve Ticari'), ('Taktiksel', 'Taktiksel'), ('Hedef İnsansız', 'Hedef İnsansız'), ('Askeri', 'Askeri')], max_length=20),
        ),
    ]
